[package]
name = "rspit"
version = "0.1.0"
edition = "2021"
authors = ["NaokiM03"]
description = "A command-line tool to run Rust snippet."
keywords = ["cli", "cargo", "tool", "command-line", "script"]
repository = "https://github.com/NaokiM03/rspit"
readme = "README.md"
license = "MIT"

[dependencies]
toml = "0.5.9"
tempdir = "0.3.7"
anyhow = "1.0.66"
sha2 = "0.10.6"
serde = "1.0.147"
serde_derive = "1.0.147"
tiny-ansi = "0.1.0"
clap = { version = "4.0.27", features = ["derive"] }
rand = "0.8.5"

[[bin]]
name = "pit"
path = "src/main.rs"
